# Generated by Django 5.1.3 on 2024-12-03 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_blogpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
