# Generated by Django 5.1.3 on 2024-12-03 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_likes_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='liked_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
