# Generated by Django 5.1.3 on 2024-12-04 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_blogpost_liked_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='liked_by_user',
            field=models.BooleanField(),
        ),
    ]
