# Generated by Django 5.1.3 on 2024-12-04 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_blogpost_liked_by_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='liked_by_user',
        ),
    ]
