# Generated by Django 5.1.3 on 2024-12-04 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_blogpost_liked_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='liked_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
